stages:
  - build
  - test

cache:
  paths:
    - vendor/

build:
  stage: build
  image: docker:git
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  only:
    refs:
      - master
  before_script:
    - echo '192.168.88.240    git.crtweb.ru' >> /etc/hosts
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE/app -f Dockerfile
    - docker push $CI_REGISTRY_IMAGE/app

test:
  stage: test
  image: $CI_REGISTRY_IMAGE/app:latest
  before_script:
    - composer install --prefer-dist --optimize-autoloader --classmap-authoritative --no-interaction --no-ansi
  script:
    - vendor/bin/phpunit --testdox --coverage-text --colors=never
